/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui;
/*******************/
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
//*******************************/


/**
 *
 * @author ha458
 */
public class Login extends javax.swing.JFrame {
    Connect con = new Connect();
    Connection connection=con.connection;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         btnsingin.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {


                try{


                    String username=txtusername.getText();
                    String password=txtpassword.getText();

//                    Statement selectStatement = connection.createStatement();
                //sql quary
//                    String sql="select * from doctor where fullName='"+username+"' and password='"+password+"'";

                    CallableStatement stmt = connection.prepareCall("{call selectdoctor(?,?)}");
                    stmt.setString(1,username);
                    stmt.setString(2,password);


                    ResultSet resultSet = stmt.executeQuery();

                    if(resultSet.next()) {
                        if(resultSet.getString("fullName").equals("Admin") && resultSet.getString("password").equals("1234")) {
//                            System.out.println("hello admin");

                            Admin admin=new Admin();
                            admin.show();
                        }else{
                            String gamil=resultSet.getString("gamil");
                            int id=resultSet.getInt("id");
                            Home h=new Home(username,password,gamil,id);
                            h.show();

                        }
                        dispose();


                    }else{
                        showMsg();
                        txtusername.setText("");
                        txtpassword.setText("");


                    }



                }catch (Exception e){
                    System.out.println(e.getMessage());

                }


//                String username=txtusername.getText();
//                String password=txtpassword.getText();
//
//
//
//                if (username.compareToIgnoreCase("hager") == 0) {
//
//                    if(password.compareTo("hager")==0){
//                        showMsg("accept");
//
//                    }else{
//                        showMsg("error password");
//
//                    }
//                }else{
//                    showMsg("error username");
//
//                }
//
            }


        });
         
   
    }
    public void showMsg(){
        JOptionPane.showMessageDialog(this,"error in username or password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        btnsingin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sign in");

        jPanel1.setPreferredSize(new java.awt.Dimension(315, 0));

        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(315, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("wellcome back");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(315, 50));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login Clinic");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(315, 100));

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 40));
        jPanel6.setLayout(new java.awt.BorderLayout());

        lblusername.setText("Username");
        lblusername.setName(""); // NOI18N
        jPanel6.add(lblusername, java.awt.BorderLayout.CENTER);

        txtusername.setPreferredSize(new java.awt.Dimension(64, 25));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel6.add(txtusername, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 40));
        jPanel7.setLayout(new java.awt.BorderLayout());

        lblpassword.setText("Password");
        jPanel7.add(lblpassword, java.awt.BorderLayout.CENTER);

        txtpassword.setPreferredSize(new java.awt.Dimension(64, 25));
        jPanel7.add(txtpassword, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel1.add(jPanel5);

        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(315, 50));

        btnsingin.setBackground(new java.awt.Color(204, 204, 204));
        btnsingin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsingin.setText("Login");
        btnsingin.setMinimumSize(new java.awt.Dimension(129, 25));
        btnsingin.setPreferredSize(new java.awt.Dimension(123, 22));
        btnsingin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnsingin, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnsingin, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login.jpg"))); // NOI18N
        jPanel2.add(jLabel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnsinginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinginActionPerformed
        // TODO add your handling code here:
//        btnsingin.addActionListener(new ActionListener(){
//            @Override
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//
//
//                try{
//
//
//                    String username=txtusername.getText();
//                    String password=txtpassword.getText();
//
////                    Statement selectStatement = connection.createStatement();
//                //sql quary
////                    String sql="select * from doctor where fullName='"+username+"' and password='"+password+"'";
//                    CallableStatement stmt = connection.prepareCall("{call selectdoctor(?,?)}");
//                    stmt.setString(1,username);
//                    stmt.setString(2,password);
//
//
//                    ResultSet resultSet = stmt.executeQuery();
//
//                    if(resultSet.next()) {
//                        if(resultSet.getString("fullName").equals("Admin") && resultSet.getString("password").equals("1234")) {
//                            System.out.println("hello admin");
//
////                            Admin admin=new Admin();
//                        }else{
//                            String gamil=resultSet.getString("gamil");
//                            int id=resultSet.getInt("id");
//                            Home h=new Home(username,password,gamil,id);
//                            h.show();
//
//                        }
//                        dispose();
//
//
//                    }else{
//                        showMsg();
//                        txtusername.setText("");
//                        txtpassword.setText("");
//
//
//                    }
//
//
//
//                }catch (Exception e){
//                    System.out.println(e.getMessage());
//
//                }
//
//
////                String username=txtusername.getText();
////                String password=txtpassword.getText();
////
////
////
////                if (username.compareToIgnoreCase("hager") == 0) {
////
////                    if(password.compareTo("hager")==0){
////                        showMsg("accept");
////
////                    }else{
////                        showMsg("error password");
////
////                    }
////                }else{
////                    showMsg("error username");
////
////                }
////
//            }
//
//
//        });
        
    }//GEN-LAST:event_btnsinginActionPerformed
   
    
    ///*********************/
    
    
    ///*****************************/
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsingin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
